data:
  data_dir: /workspace/welding_paper_project/data/bead_all_data
  frame_based: true
  max_frames: 200
  min_frame: 100
  normalize: true
  num_workers: 4
  pin_memory: true
  shuffle: true
model:
  beta_end: 0.02
  beta_schedule: linear
  beta_start: 0.0001
  feature_channels: 2
  guidance_strength: 1.0
  hidden_dim: 512
  input_channels: 3
  latent_dim: 256
  num_steps: 1000
  type: diffusion
  use_guidance: true
sampling:
  ddim_eta: 0.0
  ddim_steps: 100
  num_points: 139745
  num_samples: 10
  save_dir: result/guidance_model
system:
  device: cuda
  distributed: false
  multi_gpu: true
  precision: fp32
  save_dir: saved
  seed: 42
train:
  batch_size: 1
  epochs: 100
  gradient_clip: 1.0
  log_interval: 10
  lr: 0.0001
  optimizer: adam
  save_interval: 10
  scheduler: cosine
  weight_decay: 1.0e-05
